function tests_FivePoint_stencil()
    tests = {@test_trivial, @test_precision, @test_symmetry, @test_limiting, @test_CrossCheck};
    for t = tests
        try
            feval(t{:});
        catch E
            fprintf(2, 'Failed %s\n %s\n', func2str(t{:}), E.message)
        end
    end
end

function test_trivial()
    f = @(x) 5;
    x = 2;
    h = 0.1;
    [actual, error_estimate] = FivePoint_Stencil(f, x, h);
    expect = 0;
    tolerance = 1e-6;
    assert(abs(actual - expect) < tolerance, ...
        ['Test case trivial failed:\n', ...
         'Function: %s\n', ...
         'Point: %f\n', ...
         'Step size: %f\n', ...
         'Expected: %d\n', ...
         'Actual: %d\n', ...
         'Tolerance: %e\n'], ...
        func2str(f), x, h, expect, actual, tolerance);
    fprintf('Error Estimate: %f\n', error_estimate);
end

function test_precision()
    f = @(x) x.^2;
    x = 3;
    h = 1e-6;
    [actual, error_estimate] = FivePoint_Stencil(f, x, h);
    expect = 2 * x;
    tolerance = 1e-6;
    assert(abs(actual - expect) < tolerance, ...
        ['Test case precision failed:\n', ...
         'Function: %s\n', ...
         'Point: %f\n', ...
         'Step size: %f\n', ...
         'Expected: %d\n', ...
         'Actual: %d\n', ...
         'Tolerance: %e\n'], ...
        func2str(f), x, h, expect, actual, tolerance);
    fprintf('Error Estimate: %f\n', error_estimate);
end

function test_symmetry()
    f = @(x) x.^3;
    x = 2;
    h = 0.1;
    [actual_forward, error_estimate_forward] = FivePoint_Stencil(f, x, h);
    [actual_backward, error_estimate_backward] = FivePoint_Stencil(f, x, -h);
    
    tolerance = 1e-6;
    assert(abs(actual_forward - actual_backward) < tolerance, ...
        ['Test case symmetry failed:\n', ...
         'Function: %s\n', ...
         'Point: %f\n', ...
         'Step size: %f\n', ...
         'Forward Five-Point Stencil Derivative: %f\n', ...
         'Backward Five-Point Stencil Derivative: %f\n', ...
         'Tolerance: %e\n'], ...
        func2str(f), x, h, actual_forward, actual_backward, tolerance);
    fprintf('Error Estimate (Forward): %f\n', error_estimate_forward);
    fprintf('Error Estimate (Backward): %f\n', error_estimate_backward);
end

function test_limiting()
    f = @(x) sin(x);
    x = 0;
    h = 0.001;
    [actual, error_estimate] = FivePoint_Stencil(f, x, h);
    expect = 1;
    tolerance = 1e-6;
    assert(abs(actual - expect) < tolerance, ...
        ['Test case limiting failed:\n', ...
         'Function: %s\n', ...
         'Point: %f\n', ...
         'Step size: %f\n', ...
         'Expected: %d\n', ...
         'Actual: %d\n', ...
         'Tolerance: %e\n'], ...
        func2str(f), x, h, expect, actual, tolerance);
    fprintf('Error Estimate: %f\n', error_estimate);
end

function test_CrossCheck()
    f = @(x) 2*x + 3;
    x = 5;
    h = 0.1;
    [actual_stencil_derivative, error_estimate] = FivePoint_Stencil(f, x, h);
    actual_derivative = 2;
    tolerance = 1e-6;
    assert(abs(actual_stencil_derivative - actual_derivative) < tolerance, ...
        ['Test case CrossCheck failed:\n', ...
         'Function: %s\n', ...
         'Point: %f\n', ...
         'Step size: %f\n', ...
         'Five-Point Stencil Derivative: %d\n', ...
         'Actual Derivative: %d\n', ...
         'Tolerance: %e\n'], ...
        func2str(f), x, h, actual_stencil_derivative, actual_derivative, tolerance);
    fprintf('Error Estimate: %f\n', error_estimate);
end
