function tests_diff_quotient()
    tests = {@test_trivial, @test_precision, @test_symmetry, @test_limiting, @test_CrossCheck};
    for t = tests
        try
            feval(t{:});
        catch E
            fprintf(2, 'Failed %s\n %s\n', func2str(t{:}), E.message)
        end
    end
end

function test_trivial()
    f = @(x) 5;
    h = 0.1;
    x = 2;
    actual = diff_quotient(f, x, h);
    expect = 0;
    tolerance = 1e-5;
    assert(abs(expect - actual) < tolerance, ...
        ['Test case trivial failed:\n', ...
         'Function: %s\n', ...
         'Point: %f\n', ...
         'Step size: %f\n', ...
         'Expected: %f\n', ...
         'Actual: %f\n', ...
         'Tolerance: %e\n'], ...
        func2str(f), x, h, expect, actual, tolerance);
end

function test_precision()
    f = @(x) x.^2;
    h = 1e-6;
    x = 3;
    actual = diff_quotient(f, x, h);
    expect = 6;
    tolerance = 1e-5;
    assert(abs(expect - actual) < tolerance, ...
        ['Test case precision failed:\n', ...
         'Function: %s\n', ...
         'Point: %f\n', ...
         'Step size: %f\n', ...
         'Expected: %f\n', ...
         'Actual: %f\n', ...
         'Tolerance: %e\n'], ...
        func2str(f), x, h, expect, actual, tolerance);
end

function test_symmetry()
    f = @(x) x.^3;
    h = 0.01;
    x = -2;
    actual_forward = diff_quotient(f, x, h);
    actual_backward = -1*(diff_quotient(f, x, h));
    tolerance = 1e-5;
    assert(abs(actual_forward + actual_backward) < tolerance, ...
        ['Test case symmetry failed:\n', ...
         'Function: %s\n', ...
         'Point: %f\n', ...
         'Step size: %f\n', ...
         'Forward Difference Quotient: %f\n', ...
         'Backward Difference Quotient: %f\n', ...
         'Tolerance: %e\n'], ...
        func2str(f), x, h, actual_forward, actual_backward, tolerance);
end

function test_limiting()
    f = @(x) sin(x);
    h = 0.001;
    x = 0;
    actual = diff_quotient(f, x, h);
    expect = 1;
    tolerance = 1e-5;
    assert(abs(expect - actual) < tolerance, ...
        ['Test case limiting failed:\n', ...
         'Function: %s\n', ...
         'Point: %f\n', ...
         'Step size: %f\n', ...
         'Expected: %f\n', ...
         'Actual: %f\n', ...
         'Tolerance: %e\n'], ...
        func2str(f), x, h, expect, actual, tolerance);
end

function test_CrossCheck()
    f = @(x) 2*x + 3;
    h = 0.1;
    x = 5;
    actual_diff_quotient = diff_quotient(f, x, h);
    actual_derivative = 2;
    tolerance = 1e-5;
    assert(abs(actual_diff_quotient - actual_derivative) < tolerance, ...
        ['Test case CrossCheck failed:\n', ...
         'Function: %s\n', ...
         'Point: %f\n', ...
         'Step size: %f\n', ...
         'Difference Quotient: %f\n', ...
         'Actual Derivative: %f\n', ...
         'Tolerance: %e\n'], ...
        func2str(f), x, h, actual_diff_quotient, actual_derivative, tolerance);
end