function tests_nth_derivative()
    tests = {@test_trivial, @test_precision, @test_symmetry, @test_limiting, @test_CrossCheck};
    for t = tests
        try
            feval(t{:});
        catch E
            fprintf(2, 'Failed %s\n %s\n', func2str(t{:}), E.message)
        end
    end
end

function test_trivial()
    f = @(x) 5; 
    n = 2;
    x = 2;
    h = 0.01;
    [actual, error_estimate] = nth_derivative(f, x, h, n);
    expect = 0;
    assert(actual == expect, ...
        ['Test case trivial failed:\n', ...
         'Function: %s\n', ...
         'Point: %f\n', ...
         'Order of Derivative: %d\n', ...
         'Expected: %d\n', ...
         'Actual: %d\n'], ...
        func2str(f), x, n, expect, actual);
    fprintf('Error Estimate: %f\n', error_estimate);
end

function test_precision()
    f = @(x) x.^2;
    n = 2;
    x = 3;
    h = 0.01;
    [actual, error_estimate] = nth_derivative(f, x, h , n);
    expect = n;
    tolerance = 1e-6;
    assert(abs(actual - expect) < tolerance, ...
        ['Test case precision failed:\n', ...
         'Function: %s\n', ...
         'Point: %f\n', ...
         'Order of Derivative: %d\n', ...
         'Expected: %d\n', ...
         'Actual: %d\n', ...
         'Tolerance: %e\n'], ...
        func2str(f), x, n, expect, actual, tolerance);
    fprintf('Error Estimate: %f\n', error_estimate);
end

function test_symmetry()
    f = @(x) x.^3;
    n = 3;
    x = -2;
    h = 0.01;
    [actual_forward, error_estimate_forward] = nth_derivative(f, x, h, n);
    [actual_backward, error_estimate_backward] = nth_derivative(f, x, -h, n);
    tolerance = 1e-6;
    assert(abs(actual_forward - actual_backward) < tolerance, ...
        ['Test case symmetry failed:\n', ...
         'Function: %s\n', ...
         'Point: %f\n', ...
         'Order of Derivative: %d\n', ...
         'Forward nth Derivative: %f\n', ...
         'Backward nth Derivative: %f\n', ...
         'Tolerance: %e\n'], ...
        func2str(f), x, n, actual_forward, actual_backward, tolerance);
    fprintf('Error Estimate (Forward): %f\n', error_estimate_forward);
    fprintf('Error Estimate (Backward): %f\n', error_estimate_backward);
end

function test_CrossCheck()
    f = @(x) 2*x + 3;
    n = 1;
    x = 5;
    h = 0.01;
    [actual_nth_derivative, error_estimate] = nth_derivative(f, x, h, n);
    actual_derivative = 2;
    tolerance = 1e-10;
    assert(abs(actual_nth_derivative - actual_derivative) < tolerance, ...
        ['Test case CrossCheck failed:\n', ...
         'Function: %s\n', ...
         'Point: %f\n', ...
         'Order of Derivative: %d\n', ...
         'nth Derivative: %f\n', ...
         'Actual Derivative: %f\n', ...
         'Tolerance: %e\n'], ...
        func2str(f), x, n, actual_nth_derivative, actual_derivative, tolerance);
    fprintf('Error Estimate: %f\n', error_estimate);
end

function test_limiting()
    f = @(x) sin(x);
    n = 2;
    x = 0;
    h = 0.1;
    [actual, error_estimate] = nth_derivative(f, x, h, n);
    expect = 0;
    assert(actual == expect, ...
        ['Test case limiting failed:\n', ...
         'Function: %s\n', ...
         'Point: %f\n', ...
         'Order of Derivative: %d\n', ...
         'Expected: %d\n', ...
         'Actual: %d\n'], ...
        func2str(f), x, n, expect, actual);
    fprintf('Error Estimate: %f\n', error_estimate);
end
